kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-volume
spec:
  storageClassName: example-sc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi    